# Generated by Django 3.2.20 on 2023-08-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MTapp", "0002_appuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="status_update",
            field=models.TextField(blank=True, null=True),
        ),
    ]
