# Generated by Django 3.2.20 on 2023-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MTapp", "0003_appuser_status_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
