# Generated by Django 3.2.20 on 2023-08-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MTapp", "0004_appuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
