# Generated by Django 3.2.20 on 2023-08-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MTapp", "0005_alter_appuser_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=256, unique=True)),
                ("image", models.FileField(upload_to="")),
            ],
        ),
    ]
