# Generated by Django 3.2.20 on 2023-08-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MTapp", "0007_image_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="appuser",
            name="image",
            field=models.FileField(default="./images/defaultdp.jpg", upload_to=""),
        ),
        migrations.AddField(
            model_name="appuser",
            name="thumbnail",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
