# Generated by Django 3.2.20 on 2023-08-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MTapp", "0008_auto_20230819_1800"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="image",
            field=models.FileField(default="images/defaultdp.jpg", upload_to=""),
        ),
    ]
