# Generated by Django 3.2.20 on 2023-08-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MTapp", "0011_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="_MTapp_appuser_friends_+", to="MTapp.AppUser"
            ),
        ),
    ]
