# Generated by Django 3.2.20 on 2023-08-22 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MTapp", "0016_appuser_text_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="media",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="text_content",
        ),
        migrations.CreateModel(
            name="MediaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.ImageField(blank=True, upload_to="")),
                ("text_content", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
