# Generated by Django 3.2.20 on 2023-09-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MTapp", "0019_auto_20230823_1542"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="chat_rooms", to="MTapp.AppUser"
                    ),
                ),
            ],
        ),
    ]
