# Generated by Django 3.2.20 on 2023-09-08 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MTapp", "0020_chatroom"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
